### ISSUE TITLE
Enable AirPlay on video player

### ISSUE THREAD

**Issue by alecananian** [warnerbros/cpe-manifest-ios-experience#1]
While watching the main feature or any extra content, users should have the ability to use AirPlay to play the video on their Apple TVs

**Comment by ImranSaadi** [comment]
Available now

**Comment by ImranSaadi** [comment]
Available now

**Comment by alecananian** [comment]
Available in version tagged [3.1.0](https://github.com/warnerbros/cpe-manifest-ios-experience/releases/tag/3.1.0)
