### ISSUE TITLE
Extend library to allow for analytics plugins

### ISSUE THREAD

**Issue by ImranSaadi** [warnerbros/cpe-manifest-ios-experience#5]
Although the library already has analytics hooks in place, there's a need to quickly enable analytics. A Google Tag Manager plugin would be ideal here to allow integrators, as well as an Amazon Pinpoint & Google Firebase

**Comment by alecananian** [comment]
Documentation is now provided in the [`ExperienceDelegate` implementer](https://github.com/warnerbros/cpe-manifest-ios-experience/blob/master/Example/CPEExperienceExample/InputViewController.swift#L232) on how to respond to analytics event using your own tracking services.
